# Generated by Django 3.1.2 on 2021-04-18 12:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210413_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('vehicle_number', models.CharField(max_length=200)),
                ('driver_name', models.CharField(max_length=200)),
                ('quantity', models.FloatField(default=0)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
