# Generated by Django 3.1.2 on 2021-04-20 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='id',
        ),
        migrations.AddField(
            model_name='delivery',
            name='phone_number',
            field=models.CharField(default=9999999999, max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='product_id',
            field=models.CharField(default='A1', max_length=200, primary_key=True, serialize=False),
        ),
    ]
